name: Feature request
description: Request an enhancement to the platform
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please describe the feature in terms of: purpose, scope, and acceptance criteria.

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What pain point does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      description: What should we build? Include API sketch if relevant.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet list of what “done” means.
      value: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - low (nice to have)
        - medium (meaningful workflow improvement)
        - high (blocks adoption / correctness)
    validations:
      required: true
